### PR TITLE
wit/bindgen: Add JSON tag to Record structs

### PR DESCRIPTION
**Pull request by lxfontes**
Related to #239 

`HostLayout` receives `json:"-"` and any other field receives the original wit name.

```
// DateTime represents the record "wasi:clocks/wall-clock@0.2.0#datetime".
//
// A time and date in seconds plus nanoseconds.
//
//	record datetime {
//		seconds: u64,
//		nanoseconds: u32,
//	}
type DateTime struct {
	_           cm.HostLayout `json:"-"`
	Seconds     uint64        `json:"seconds"`
	Nanoseconds uint32        `json:"nanoseconds"`
}
```

### CODE REVIEW

**Comment by ydnar** [comment]
Don't forget to `go generate ./tests/...`

**Comment by ydnar** [comment]
How do we want to think about zero-value structs? Do we want to serialize, or have `omitzero` or `omitempty`?

**Comment by lxfontes** [comment]
Ideally I'd like `omitzero`, however by adding it we complicate:
- Tuples: encoded as lists. need to make sure we emit `[ "field0", null, "field2"]` and not `["field0","field2"]`. Encoding it as dictionary would couple the json keys to `cm.Tuple` field names. I rather keep them as lists.
- Enums/Variants: The zero value is valid. I feel this is by WIT design so the first value acts as a sentinel, but it is up to developers to actually use it that way.

feels like `omitempty` would be the least problematic, not raising the issues above.

For now I'm adding `omitempty` and we can revisit if needed after addressing Variant encoding.

**Comment by ydnar** [comment]
Given that Go omits fields tagged with `omitempty` that are the zero value for the type, this may not be what we want.

Maybe we start without `omitempty` and then add it in certain cases as an optimization?

**Comment by lxfontes** [comment]
👍 
removed `omitempty`.

**Comment by ydnar** [comment]
Looks ready to merge! Can you add a note to CHANGELOG.md?

**Review by ydnar — APPROVED** [review]

**Review by ydnar — APPROVED** [review]

**Pull request merged**
